steps:
  - name: node:16.7.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
    - 'TOKEN=${_TOKEN}'
    - 'MONGO_URI=${_MONGO_URI}'
    - 'WEB3_URI=${_WEB3_URI}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/keeper:$SHORT_SHA',
        '--cache-from',
        'gcr.io/$PROJECT_ID/keeper:develop',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/keeper:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'keeper', '--image', 'gcr.io/$PROJECT_ID/keeper:$SHORT_SHA', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
 - 'gcr.io/$PROJECT_ID/keeper'
timeout: 600s
options:
  dynamic_substitutions: true